- graph_menu.php
ref https://community.openenergymonitor.org/t/emoncms-graph-module-developments/1380/4
> Added "Graph" to the emoncms setup menu

- graph.js
- graph_controller.php
- view.php
New additions:
- Ability to open the graph view with multiple feeds specified in the URL
- Ability to view public feeds in the graph interface without login
- Improved responsive design for graph options and statistics view
> Merge of development branch

- graph.js
- graph_controller.php
- view.php
- UI improvements for mobile use
- View public feeds without login
> Merge master into stable

- widget/graph_widget.php
This is the second part of the fix for the issue described here: 
https://github.com/emoncms/emoncms-docker/issues/11
"works for me" - but I don't fully understand what this group thing-y, so please someone more knowledgeable review this :)
> Fixing error message in dashboard view

- embed.php
- graph.js
- group_view.php
- view.php
- vis.helper.js
At a high level, changes as follows:
1. Change tooltip to show give context related info, e.g. for a daily stat only show YMD
2. Add support for touch devices within flot
3. Change the Interval to display and accept human readable figures, e.g. 1d, 2w, 4h
4. Set the minTickSize to align with the YMD intervals
5. bar position is placed to the right for 'delta' to help show what time duration this covers
6. Store the requesttype, e.g. fixed, daily, weekly ...
7. Align the start/ end dates to show the entire bar
>  Graph tooltip, display and interval enhancements 

- graph.js
> added check against unavailable feed units

- graph.css
- graph.js
- view.php
**I got it to work!! :)**
previous discussions: 
- graph issue #9 
- graph pull request #47 
- https://github.com/emoncms/emoncms/issues/979
2 axis graph with split graph legend to associate left and right axis with relevant feed data
`graph.css` is used to style the legend positions.
> 2 col legend test

- graph.css
- graph.js
- view.php
fix issue #29 - collapsible stats table
> made graph stats table collapsible

- graph.css
- graph.js
- view.php
> added button classes and matching css entries

- group_view.php
- view.php
Enlarge areas for French localization
> Enlarge areas

- graph.css
fix #64 
i've increased the padding on the right for the right-side legend
> increased right side legend right padding

- graph_model.php
Fix issue on regular expression containing an hyphen. Please see PR 1180 of emoncms/emoncms
> fix php7.3 regexp hyphen

- graph.js
A plot type I found missing from graph.
> Added plot type 'points'

- graph.js
- view.php
checked for feed availability before displaying data
added translation placeholders for user messages
fix #83
> checked for user session before requesting user timezone

- graph.js
see: https://github.com/emoncms/emoncms/issues/1245
> enabled tabindex for <th> sidebar feed names

- embed.php
the navigation buttons now work as expected on embedded graphs
> corrected the time window attribute on the <button>

- view.php
> changed path to vue.js file

- embed.php
- group_view.php
related to emoncms pull request that adds a `emoncms.js` file.
https://github.com/emoncms/emoncms/pull/1404
> used global js path varialbe

- embed.php
- graph.js
- view.php
corrected the translation placeholders
moved printdate() to graph.js
fix #107
> fixed missing vue.js script on embed template

- graph.js
- view.php
Fix and add localizations.
Before :
After : 
Before : 
After :
> Improve localization 10 2019

- graph_menu.php
Add title localization
Before : 
After :
> Sidebar localization for graph module

- embed.php
This change was missed from 3bd9e691f11e7d42f911d1b9cf091459e9acee36 and breaks zoom/pan on dashboards.
> minimum feed interval setting for embeds
